workdir: "./data/demo"
ba_lr: 1e-4
cp_translation_dyn_lr: 1e-2
intrinsics_lr: 1e-4
num_init_epochs: 600
num_BA_epochs: 2000
num_motion_start_epochs: 300
num_dyn_epochs: 1000
reproj_weight: 1.0
pose_smooth_weight_t: 1.0
pose_smooth_weight_r: 1.0
dyn_smooth_weight_t: 10.0
dyn_laplacian_weight_t: 100.0
experiment_name: base_gt_K
log: True
opt_intrinsics: False
depth_dir: "unidepth"
cotracker_path: "densetrack3d_efep"
dyn_mask_dir: "deva"
video: None
loss_fn: "l1"
deterministic: True
seed: 42
depth_version: "v1"
global_downsample_rate: 8
save_upsample: False
use_sampson: False